module.exports = {
  HOME: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  FORGOT_PASSWORD: "/forgot-password",
  BRANCH: "/branch",
  BOOKING: "/booking",
  BOOKING_HCM_D1: "/booking/hcm/d1",
  BOOKING_HCM_D7: "/booking/hcm/d7",
  BOOKING_HN_NTL: "/booking/hcm/ntl",
  STORY: "/story",
  CONTACT: "/contact",
  ANDROID: "https://play.google.com/store/apps/details?id=com.dym.medical",
  IOS: "https://apps.apple.com/app/dym-medical/id6449171708",
};
