module.exports = {
  HOME: "/",
  LOGIN: "/#",
  REGISTER: "/#",
  FORGOT_PASSWORD: "/#",
  BOOKING: "/booking",
  BOOKING_HCM_D1: "/booking/hcm/d1",
  BOOKING_HCM_D7: "/#",
  BOOKING_HN_NTL: "/#",
  APPOINTMENT: "/booking/appointment",
  STORY: "/#",
  CONTACT: "/#",
  ANDROID: "https://play.google.com/store/apps/details?id=com.dym.medical",
  IOS: "https://apps.apple.com/app/dym-medical/id6449171708",
};
